services:
  - name: api
    type: web
    env: docker
    plan: free
    buildCommand: cd apps/api && docker build -t api .
    startCommand: pnpm run start:production
    envVars:
      - key: REDIS_URL
        fromDatabase: redis-instance
    dockerfilePath: apps/api/Dockerfile
    healthCheckPath: /
    autoDeploy: true
    instances: 1
    ports:
      - port: 3002
        protocol: tcp

  - name: worker
    type: worker
    env: docker
    plan: free
    buildCommand: cd apps/api && docker build -t worker .
    startCommand: pnpm run workers
    envVars:
      - key: REDIS_URL
        fromDatabase: redis-instance
    dockerfilePath: apps/api/Dockerfile
    autoDeploy: true
    instances: 1

  - name: playwright-service
    type: web
    env: docker
    plan: free
    buildCommand: cd apps/playwright-service-ts && docker build -t playwright-service .
    startCommand: node server.js
    envVars:
      - key: REDIS_URL
        fromDatabase: redis-instance
      - key: PORT
        value: "3000"
      - key: PROXY_SERVER
        value: ${PROXY_SERVER}
      - key: PROXY_USERNAME
        value: ${PROXY_USERNAME}
      - key: PROXY_PASSWORD
        value: ${PROXY_PASSWORD}
      - key: BLOCK_MEDIA
        value: ${BLOCK_MEDIA}
    dockerfilePath: apps/playwright-service-ts/Dockerfile
    healthCheckPath: /
    autoDeploy: true
    instances: 1
    ports:
      - port: 3000
        protocol: tcp
